# Generated by Django 5.0.3 on 2024-06-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChangePass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("oldpass", models.CharField(max_length=50)),
                ("newpass", models.CharField(max_length=50)),
                ("compass", models.CharField(max_length=50)),
            ],
        ),
    ]
