# Generated by Django 5.1 on 2024-11-03 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authuser", "0002_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
