# Generated by Django 5.1 on 2024-11-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_checkout"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("out of delivery", "out of delivery"),
                    ("delivered", "delivered"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
